config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :worlds
  get 'worlds/:id/showa', to: 'worlds#showa'
  get 'worlds/:id/showb', to: 'worlds#showb'
  get 'worlds/:id/darkmode', to: 'worlds#darkmode', as: "dark"
  get 'worlds/:id/lightmode', to: 'worlds#lightmode', as: "light"
  get 'worlds/:id/planttint', to: 'worlds#planttint' 
  get 'worlds/index', to: 'worlds#index' 
  get 'worlds/', to: 'worlds#index' 
  get 'worlds/:id', to: 'worlds#show' 
  puts 'worlds/:id/planttint', to: 'worlds#updateplant'
  post 'worlds/:id/planttint', to: 'worlds#edit'

  get '/plants', to: 'plants#index'
  get 'plants/create', to: 'plants#create'
  get 'plants/:id/edit', to: 'plants#edit', as: "plant_edit"
  get 'weathers/:id/edit', to: 'weathers#edit'
  get 'plants/new', to: 'plants#new'

  get 'weathers/createsun', to: "weathers#create"
  get 'weathers/destroysun', to: "weathers#destroy"
  get 'weathers/', to: "weathers#index"
  get 'weathers/index', to: "weathers#index"

  get 'weathers/new', to: "weathers#create"
  get 'weathers/create', to: "weathers#create"
  post 'weathers/createsun', to: "weathers#create"

  post 'plants/create', to: 'plants#create'
  patch 'plants/:id/edit', to: 'plants#update'
  patch 'weathers/:id/edit', to: 'weathers#update'
  post 'plants/new', to: 'plants#new'

  post 'plants/', to: 'plants#index'


  get '/signup', to: "gods#new"
  post '/signup', to: "gods#create"

  get '/login', to: "auth#signin"
  post '/login', to: "auth#verify"


  get '/logout', to: "auth#logout"
root 'worlds#index'

  resources :plants

 # get '/plants/new' => 'plants#new'
#resources :worlds, only: [:showa, :showb]
end

app/models/plant.rb
class Plant < ApplicationRecord


    validates :g, :r, :b, presence: true
    validates :r, numericality: true
    validates :r, numericality: { greater_than_or_equal_to: 0 }
    validates :r, numericality: { less_than_or_equal_to: 255 }
    validates :g, numericality: true
    validates :g, numericality: { greater_than_or_equal_to: 0 }
    validates :g, numericality: { less_than_or_equal_to: 255 }
    validates :b, numericality: true
    validates :b, numericality: { greater_than_or_equal_to: 0 }
    validates :b, numericality: { less_than_or_equal_to: 255 }
    belongs_to :path
    has_many :eggs, as: :pod




    def self.average_energy
            x = 0
            Plant.all.each do |plant| x += plant.energy end
                avg = (x.to_f/Plant.all.length)
                avg
    end



end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

    before_action :redirect_god



    def new
        @plant = Plant.new
    end




    def index   
        @plants  = Plant.all
        @average = Plant.average_energy
        #the line below this was an attempt to produce the colors in the color
#<%=    Rainbow(" R: #{plant.r}, G: #{plant.g}, B: #{plant.b}").color(colorstring)                     %>
end


def create
    @plant = Plant.new
    @plant.r = params[:plant][:r]
    @plant.g = params[:plant][:g]
    @plant.b = params[:plant][:b]
    @plant.depth = 0
    @plant.energy = 10950
    @plant.growthrate = 50
    @plant.status = 1
    @plant.typisch = 7
    @plant.name = 7
    @plant.status = 1
    @plant.inventory = 10000
    @plant.save
end



def edit   
    @plant = Plant.new
end

def update

   @plant = Plant.all[rand(Plant.all.length)]
    @plant.r = params[:plant][:r]
    @plant.g = params[:plant][:g]
    @plant.b = params[:plant][:b]
    @plant.energy = 10950
    @plant.inventory = 10000
    
    
    if @plant.save
    redirect_to plants_path
    else    
        flash[:message] = "Be serious, 0 through 255"
        redirect_to '/plants/1/edit'
    end
end



end

app/helpers/plant_helper.rb
module PlantHelper
end

app/views/plants/edit.html.erb
<h1> Change a plant to a set of R G B values</h1>


<%= button_to "Return to world", world_path(1), method: :get%>
<br>
<br>
<br>

<%=   flash[:message] %>

<%= form_for Plant.all.first do |t|%>
<%= t.label :r  %>
<%= t.number_field :r %>
<%= t.label :g  %>
<%= t.number_field :g %>
<%= t.label :b  %>
<%= t.number_field :b %>
<%= t.submit %>
<% end %>

app/views/plants/index.html.erb
<h1> All plants</h1>


<%= button_to "Return to world", world_path(1), method: :get%>
<br>

    <%= button_to "Edit Random Plant", plant_edit_path(1), method: :get%>
<br>
<br>

<%= "The Plants Average Energy is #{@average} "%>
<br>
<br>


<% @plants.each do |plant|%>
<%= " Plant at X: #{plant.path.x}, Y: #{plant.path.y}, Has"%><br>


<%  bigred =(plant.r/16).to_i          %>

<%  tinred = (plant.r%16)           %>

<%  biggreen = (plant.g/16).to_i          %>

<%  tingreen = (plant.g%16)           %>

<%  bigblue =(plant.b/16).to_i          %>

<%  tinblue = (plant.b%16)           %>



<%  bigredx = 15-(plant.r/16).to_i          %>

<%  tinredx = 15-(plant.r%16)           %>

<%  biggreenx = 15-(plant.g/16).to_i          %>

<%  tingreenx = 15-(plant.g%16)           %>

<%  bigbluex = 15-(plant.b/16).to_i          %>

<%  tinbluex = 15-(plant.b%16)           %>


<%  colorstring = "#" + bigred.to_s(16) +    tinred.to_s(16) +    biggreen.to_s(16) +    tingreen.to_s(16) +    bigblue.to_s(16) +    tinblue.to_s(16)  %>

<%  colorstringx = "#" + bigredx.to_s(16) +    tinredx.to_s(16) +    biggreenx.to_s(16) +    tingreenx.to_s(16) +    bigbluex.to_s(16) +    tinbluex.to_s(16)  %>


<div style="background-color: <%=colorstring%> ;color: <%=colorstringx%>"> 
<%= " R: #{plant.r}, G: #{plant.g}, B: #{plant.b}, Energy:#{plant.energy}"%><br>

</div>

<%end%>

app/views/plants/new.html.erb
<h1> New plants by a set of R G B values</h1>



<%= button_to "Return to world", world_path(1), method: :get%>
<br>
<br>
<br>

<%= form_for @plant do |t|%>
<%= t.label :r  %>
<%= t.number_field :r %>
<%= t.label :g  %>
<%= t.number_field :g %>
<%= t.label :b  %>
<%= t.number_field :b %>
<%= t.submit %>
<% end %>